# Generated by Django 3.2.7 on 2021-09-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_workplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_modified']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['last_modified']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['last_modified']},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['last_modified']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='created_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='created_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='workplace',
            old_name='created_at',
            new_name='last_modified',
        ),
    ]
