# Generated by Django 3.2.7 on 2021-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210905_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
