# Generated by Django 3.2.7 on 2021-09-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210905_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
