# Generated by Django 3.2.7 on 2021-09-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210927_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.role'),
            preserve_default=False,
        ),
    ]
