# Generated by Django 3.2.7 on 2021-11-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bounding_key',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FreeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('days_from', models.DateField()),
                ('days_to', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_days', to='api.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
