# Generated by Django 3.2.7 on 2021-11-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211123_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='time_job',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='time_closes',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='time_opens',
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='api.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
