# Generated by Django 3.2.7 on 2021-12-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_employee_bounding_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='preffered_roles',
            new_name='possible_roles',
        ),
    ]
